module.exports = {
  STREAMLABS_CLIENT_ID: 'YOUR_STREAMLABS_CLIENT_ID',
  STREAMLABS_CLIENT_SECRET: 'YOUR_STREAMLABS_CLIENT_SECRET',
  STREAMLABS_CALLBACK_URL: 'YOUR_STREAMLABS_CALLBACK_URL',
  MONGO_URI: 'YOUR_MONGODB_LOCATION',
  SESSION_SECRET: 'YOUR_SESSION_SECRET',
};
