module.exports = {
  TWITCH_ACCESS_TOKEN: process.env.TWITCH_ACCESS_TOKEN,
  TWITCH_REFRESH_TOKEN: process.env.TWITCH_REFRESH_TOKEN,
  TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET: process.env.TWITCH_CLIENT_SECRET,
  TWITCH_CALLBACK_URL: process.env.TWITCH_CALLBACK_URL,
  TWITCH_ACCOUNT_ID: process.env.TWITCH_ACCOUNT_ID,
  MONGO_URI: process.env.MONGO_URI,
  SESSION_SECRET: process.env.SESSION_SECRET,
};
